[project]
name = "pyPalace"
version = "0.1.0"
description = "A code suite to automate the generation of AWS Palace config files"
authors = [
    { name = "Firas Abouzahr" }
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["numpy","pandas"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

